apiVersion: v1
kind: Service
metadata:
  name: lua-server
  labels:
    name: lua-server
#    app: droi-markert
spec:
  type: NodePort
  ports:
  - port: 8000
    name: lua
    targetPort: 8000
  - port: 8001
    name: lua-market-old
    targetPort: 8001
  - port: 8888
    name: lua-test
    targetPort: 8888
  selector:
    name: lua-server
#    app: droi-markert
