# This viminfo file was generated by Vim 7.3.
# You may edit it if you're careful!

# Value of 'encoding' when this file was written
*encoding=utf-8


# hlsearch on (H) or off (h):
~H
# Last Search Pattern:
~MSle0~/ directory

# Last Substitute Search Pattern:
~MSle0&^

# Last Substitute String:
$

# Command Line History (newest to oldest):
:q
:au
:Q
:w
:GoInstallBinaries
:NERDTree é–‹å•Ÿ
:wq
:noh
:nog
:'<,'>s/^/\"/g
:'<,'>s/^/\t/g
:'<,'>%s/^/\"/g
:'<,'>%s/^/"/g
:PlugInstall
:Wq
::q
:W
:38
:14
:WQ

# Search String History (newest to oldest):
?/ directory
?/pluginstall
?/mkdir
?/bin
?/setup_structure
?/go
?/logv
?/===
?/\\t
?/\t
?/bin_dir
?/path
?/ls
?/rm
?/##
?/nodejs
?/tmpstr
?/check_projects
?/config
? ^

# Expression History (newest to oldest):

# Input Line History (newest to oldest):

# Input Line History (newest to oldest):

# Registers:
""0	LINE	0
	
"1	LINE	0
	
"2	LINE	0
	
"3	LINE	0
	
"4	LINE	0
	
"5	LINE	0
	
"6	LINE	0
	- [VimScript hardway](http://learnvimscriptthehardway.stevelosh.com/)
"7	LINE	0
	
"8	LINE	0
	"endtry
"9	LINE	0
	"catch
"q	CHAR	0
	;
"-	CHAR	0
	 

# File marks:
'0  13  0  ~/project/go_project/src/github.com/gogits/gogs/gogs.go
'1  31  0  ~/project/go_project/src/github.com/gogits/gogs/gogs.go
'2  1  0  ~/project/go_project/src/github.com/gogits/gogs/gogs.go
'3  30  0  ~/NERD_tree_2
'4  41  0  ~/project/go_project/src/github.com/gogits/gogs/gogs.go
'5  1  0  ~/project/go_project/src/github.com/gogits/gogs/NERD_tree_2
'6  72  0  ~/NERD_tree_2
'7  2  1  ~/tmp.go
'8  1  0  ~/tmp.go
'9  7  0  ~/project/env_setup/vim/README.md

# Jumplist (newest first):
-'  13  0  ~/project/go_project/src/github.com/gogits/gogs/gogs.go
-'  31  0  ~/project/go_project/src/github.com/gogits/gogs/gogs.go
-'  21  0  ~/NERD_tree_2
-'  19  2  
-'  1  0  
-'  1  0  ~/project/go_project/src/github.com/gogits/gogs/gogs.go
-'  41  0  ~/project/go_project/src/github.com/gogits/gogs/gogs.go
-'  30  0  à·¾ù
-'  42  2  
-'  37  2  
-'  37  2  ~/project/go_project/src/github.com/gogits/gogs/NERD_tree_1
-'  1  0  ~/project/go_project/src/github.com/gogits/gogs/NERD_tree_1
-'  74  2  
-'  2  1  
-'  1  0  
-'  1  0  
-'  2  0  
-'  1  0  
-'  116  1  
-'  122  0  n
-'  1  0  	
-'  2  0  °¡¾ù
-'  99  0  
-'  1  16  ã£¾ù
-'  17  0  Ÿ¾ù
-'  1  0  
-'  1  0  
-'  21  0  ~/NERD_tree_2
-'  25  2  ~/NERD_tree_2
-'  1  0  ~/NERD_tree_2

# Buffer list:
%~/project/go_project/src/github.com/gogits/gogs/gogs.go	13	0

# History of marks within files (newest to oldest):

> ~/project/go_project/src/github.com/gogits/gogs/gogs.go
	"	13	0

> ~/project/go_project/src/github.com/gogits/gogs/NERD_tree_1
	"	15	0
	.	1	0
	+	1	0
	+	1	0

> ~/NERD_tree_1
	"	1	0
	.	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0

> ~/NERD_tree_2
	"	21	0
	.	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0

> ~/project/go_project/src/github.com/gogits/NERD_tree_1
	"	1	0
	.	1	0
	+	1	0

> ~/project/go_project/src/github.com/gogits/gogs/NERD_tree_2
	"	1	0
	.	1	0
	+	1	0

> ~/tmp.go
	"	2	1
	^	2	2
	.	2	1
	+	1	2
	+	2	1

> ~/project/code_sandbox/go-cobra/main.go
	"	1	0

> ~/project/code_sandbox/go-cobra/NERD_tree_1
	"	3	1
	.	1	0
	+	1	0
