#!/bin/bash
# output docker container name , ip , and id to file

IFS=$'\n'
c_info=($(docker ps --format="{{.Names}}\\t{{.ID}}"))

for c_vars in "${c_info[@]}" 
do
    c_name=$(echo -e "$c_vars" | awk '{print $1}')
    ip=$(docker exec -it $c_name /bin/bash -c "hostname -I")
    echo -e "$c_vars\t$ip"
done



